on: push
name: ğŸš€ Deploiement de site web
jobs:
  web-deploy:
    name: ğŸ‰ Deploiement
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Obtenir le code
      uses: actions/checkout@v4
    
    - name: ğŸ“‚ Synchronisation de fichiers
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.url }}
        username: ${{ secrets.groupe }}
        password: ${{ secrets.mdp }}
        port: ${{ secrets.port }}
